[tools]
bun = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
gradle = "latest"
groovy = "latest"
java = "latest"
jq = "latest"
lua-language-server = "latest"
neovim = "latest"
opencode = "latest"
python = "latest"
ripgrep = "latest"
uv = "latest"
zig = "latest"
zls = "latest"
